WebAdminHra/Controllers/RolController.cs
using Dominio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebAdminHra.Controllers
{
    public class RolController : Controller
    {
        private readonly HRAContext context;
        public RolController(HRAContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index(string buscar = "")
        {
            IQueryable<Rol> qry = context.Rol;
            if (!string.IsNullOrWhiteSpace(buscar))
                qry = qry.Where(x => x.Denominacion.Contains(buscar));

            var roles = await qry.ToListAsync();

            return View(roles);
        }
        public async Task<IActionResult> Crear(int id = 0)
        {
            var obj = new Rol() { Estado = true };
            var menus = new List<Models.ItemCheckBox>();

            if (id > 0) { 
                obj = await context.Rol.FirstOrDefaultAsync(x => x.RolId == id);
                var menusSeleccionados = await context.RolMenu.Where(x => x.RolId == id).ToListAsync();
                var menusbd = await context.Menu.Where(x => x.IndPadre == false).ToListAsync();

                menus = menusbd.Select(x => new Models.ItemCheckBox
                {
                    Id = x.MenuId,
                    Denominacion = x.Modulo + "/" + x.Denominacion,
                    EsSeleccionado = menusSeleccionados.Any(y => y.MenuId == x.MenuId)
                }).OrderBy(x => x.Denominacion).ToList();
            }

            return View(new Dto.RolCreacionDto
            {
                RolId = obj!.RolId,
                Denominacion = obj.Denominacion,
                Estado= obj.Estado,
                Menus= menus
            });
        }
        [HttpPost]
        public async Task<IActionResult> Guardar(Dto.RolCreacionDto rol)
        {

            if (rol.RolId == 0)
                context.Rol.Add(new Rol { Denominacion = rol.Denominacion, Estado = rol.Estado });
            else
                context.Rol.Update(new Rol { RolId = rol.RolId, Denominacion = rol.Denominacion, Estado = rol.Estado });

            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> GuardarMenu(int RolId, List<Models.ItemCheckBox> menus)
        {
            
            var rol = await context.RolMenu.Where(x => x.RolId == RolId).ToListAsync();
            context.RolMenu.RemoveRange(rol);
            await context.SaveChangesAsync();


            var r = menus.Where(x => x.EsSeleccionado)
                        .Select(x => new RolMenu() { RolId = RolId, MenuId = x.Id });
            context.RolMenu.AddRange(r);
            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

WebAdminHra/Views/Rol/Crear.cshtml
@model WebAdminHra.Dto.RolCreacionDto 

<div class="row">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Gestion de Roles</h4>
                <hr />
                <form class="needs-validation" novalidate action="@Url.Action("Guardar","Rol")" method="post">
                    <input type="hidden" asp-for="RolId" />
                    <div class="row">
                        <div class="col-md-3">
                            <div class="mb-3">
                                <label asp-for="Denominacion" class="form-label">Denominacion</label>
                                <input type="text" class="form-control" asp-for="Denominacion"
                                       placeholder="Denominacion" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" asp-for="Estado">
                        <label class="form-check-label" asp-for="Estado">
                            Activo
                        </label>
                    </div>
                    <div>
                        <button class="btn btn-primary" type="submit">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@if (Model.Menus.Count > 0)
{
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Gestion de Menus</h4>
                    <hr />
                    @using (Html.BeginForm("GuardarMenu", "Rol", FormMethod.Post))
                    {
                        @Html.HiddenFor(x=>Model.RolId)
                        @for (var i = 0; i < Model.Menus.Count; i++)
                        {
                            <div>
                                <input type="hidden" asp-for="Menus[i].Id" />
                                <input class="form-check-input" type="checkbox" asp-for="Menus[i].EsSeleccionado">
                                <label class="form-check-label" asp-for="Menus[i].EsSeleccionado">
                                    @Model.Menus[i].Denominacion
                                </label>
                            </div>
                        }
                        <div>
                            <button class="btn btn-primary" type="submit">Guardar</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

WebAdminHra/Views/Rol/Index.cshtml
@model List<Dominio.Rol>

<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">Mantenimiento de Roles</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-4">
                        <form action="@Url.Action("Index","Rol")">
                            <div class="search-box me-2 mb-2 d-inline-block">
                                <div class="position-relative">
                                    <input type="text" name="buscar" class="form-control" placeholder="Buscar...">
                                    <i class="bx bx-search-alt search-icon"></i>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-8">
                        <div class="text-sm-end">
                            <a href="@Url.Action("Crear","Rol",new{id=0})" class="btn btn-success btn-rounded waves-effect waves-light mb-2 me-2">
                                <i class="mdi mdi-plus me-1"></i>
                                Crear Rol
                            </a>
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">
                    <table class="table align-middle table-nowrap table-check">
                        <thead class="table-light">
                            <tr>
                                <th class="align-middle">ID</th>
                                <th class="align-middle">Denominacion</th>
                                <th class="align-middle">Estado</th>
                                <th class="align-middle">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.RolId</td>
                                    <td>@item.Denominacion</td>                                    
                                    <td>
                                        <span class="badge badge-pill badge-soft-success font-size-12">@(item.Estado?"ACTIVO":"INACTIVO")</span>
                                    </td>
                                    <td>
                                        <div class="d-flex gap-3">
                                            <a href="@Url.Action("Crear","Rol",new {id=item.RolId})" class="text-success"><i class="mdi mdi-pencil font-size-18"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>